import JSP000404Research.CriticalPhaseInterval
import JSP000404Research.MinimalPhaseCover
import Mathlib.Tactic

/-!
# Critical bad intervals inside an irredundant cover

A critical obstruction generated by a transition gap with anchor alpha and
width s has bad interval

  [alpha + s - 1, alpha + delta].

For fixed alpha all such intervals share the same right endpoint.  Hence two
distinct intervals with the same anchor are necessarily nested.  An
irredundant cover cannot contain both, because every chosen interval owns a
private phase.

This is the key compression missing from the earlier "count all critical
intervals" route: if geometry assigns every obstruction to a hull-turn slot in
such a way that one slot fixes the anchor alpha, then an irredundant subcover
uses each slot at most once.  The many redundant critical intervals visible in
counterexamples become harmless.
-/

namespace JSP000404Research

/-- Bad-phase predicate for a family of critical transition intervals. -/
def CriticalBadAt
    {I : Type*}
    (alpha s : I → ℝ) (delta : ℝ)
    (i : I) (x : ℝ) : Prop :=
  criticalBadLeft (alpha i) (s i) ≤ x ∧
    x ≤ criticalBadRight (alpha i) delta

/-- Two critical bad intervals with the same anchor have the same right
endpoint. -/
theorem criticalBadRight_eq_of_anchor_eq
    {I : Type*}
    (alpha : I → ℝ) (delta : ℝ)
    {i j : I}
    (hanchor : alpha i = alpha j) :
    criticalBadRight (alpha i) delta =
      criticalBadRight (alpha j) delta := by
  rw [hanchor]

/-- In an irredundant critical cover, distinct chosen obstructions must have
distinct anchors. -/
theorem critical_anchor_ne_of_irredundant
    {I : Type*} [DecidableEq I]
    (alpha s : I → ℝ) (delta : ℝ)
    (S : Finset I)
    (hmin : IrredundantCover (CriticalBadAt alpha s delta) S)
    {i j : I}
    (hi : i ∈ S) (hj : j ∈ S) (hij : i ≠ j) :
    alpha i ≠ alpha j := by
  intro hanchor
  let L : I → ℝ := fun q => criticalBadLeft (alpha q) (s q)
  let R : I → ℝ := fun q => criticalBadRight (alpha q) delta
  have hmin' :
      IrredundantCover (InClosedInterval L R) S := by
    simpa [CriticalBadAt, InClosedInterval, L, R] using hmin
  have hReq : R i = R j := by
    dsimp [R]
    exact criticalBadRight_eq_of_anchor_eq alpha delta hanchor
  rcases le_total (L i) (L j) with hL | hL
  · have hstrict :=
      irredundant_interval_right_strict
        L R S hmin' hi hj hij hL
    linarith
  · have hstrict :=
      irredundant_interval_right_strict
        L R S hmin' hj hi hij.symm hL
    linarith

/-- If equal hull-slot labels force equal critical anchors, then the slot label
is injective on every irredundant critical cover. -/
theorem critical_slot_injective_on_irredundant
    {I Slot : Type*} [DecidableEq I]
    (alpha s : I → ℝ) (delta : ℝ)
    (slot : I → Slot)
    (S : Finset I)
    (hmin : IrredundantCover (CriticalBadAt alpha s delta) S)
    (hslot_anchor :
      ∀ {i j : I}, slot i = slot j → alpha i = alpha j) :
    ∀ {i j : I}, i ∈ S → j ∈ S →
      slot i = slot j → i = j := by
  intro i j hi hj hslot
  by_contra hij
  exact critical_anchor_ne_of_irredundant
    alpha s delta S hmin hi hj hij
    (hslot_anchor hslot)

/-- Finite-slot cardinality outlet.  Once geometry supplies a slot map whose
fibres have a common critical anchor, every irredundant obstruction cover has
at most as many members as there are slots. -/
theorem critical_irredundant_card_le_slots
    {I Slot : Type*} [DecidableEq I] [Fintype Slot]
    (alpha s : I → ℝ) (delta : ℝ)
    (slot : I → Slot)
    (S : Finset I)
    (hmin : IrredundantCover (CriticalBadAt alpha s delta) S)
    (hslot_anchor :
      ∀ {i j : I}, slot i = slot j → alpha i = alpha j) :
    S.card ≤ Fintype.card Slot := by
  classical
  let f : {i : I // i ∈ S} → Slot := fun i => slot i.1
  have hf : Function.Injective f := by
    intro i j hij
    apply Subtype.ext
    apply critical_slot_injective_on_irredundant
      alpha s delta slot S hmin hslot_anchor
      i.2 j.2
    exact hij
  have hcard :=
    Fintype.card_le_of_injective f hf
  simpa [f] using hcard

#print axioms critical_anchor_ne_of_irredundant
#print axioms critical_slot_injective_on_irredundant
#print axioms critical_irredundant_card_le_slots

end JSP000404Research
