import JSP000404Research.CanonicalSignGap
import JSP000404Research.CriticalAngleExcess
import JSP000404Research.SmallSameSignGapAngle
import Mathlib.Tactic

/-!
# Actual angle of a concrete sign-transition gap

A terminal phase obstruction is generated by an actual adjacent projective
ray gap whose lifted endpoint signs are opposite.

For an ordinary sorted pair j,k with canonical signs different, the genuine
angle at the centre is exactly

  pi - (theta_k-theta_j).

For the cyclic wrap pair last,first, a lifted sign transition means

  sign(last) != !sign(first),

and the genuine angle is exactly

  pi - (theta_first + pi - theta_last).

After Sendov normalization lambda=pi/t, if s denotes the normalized projective
gap width, both identities become

  angle = pi - s*lambda.

Consequently the bad-phase width 1+delta-s is exactly the physical angle
excess above the baseline (n-1)*lambda.

This is the concrete bridge from terminal transition obstructions to the
remaining global large-angle-excess budget.
-/

namespace JSP000404Research

open Real

/-- Exact actual angle across an ordinary canonical sign transition. -/
theorem actual_angle_eq_pi_sub_ordinary_gap_of_sign_ne
    {V : Type*} {p : V → Plane}
    (hp : Function.Injective p)
    (i : V)
    {j k : OtherVertex i}
    (horder : rayThetaAt hp i j ≤ rayThetaAt hp i k)
    (hsign : raySignAt hp i j ≠ raySignAt hp i k) :
    EuclideanGeometry.angle (p j.1) (p i) (p k.1) =
      Real.pi -
        (rayThetaAt hp i k - rayThetaAt hp i j) := by
  have hbounds :=
    canonical_parameter_gap_bounds hp i horder
  have habs :
      |rayThetaAt hp i j - rayThetaAt hp i k| =
        rayThetaAt hp i k - rayThetaAt hp i j := by
    rw [abs_of_nonpos]
    · ring
    · linarith
  change
    InnerProductGeometry.angle
        (p j.1 - p i) (p k.1 - p i) =
      Real.pi -
        (rayThetaAt hp i k - rayThetaAt hp i j)
  rw [rayRepAt_eq hp i j, rayRepAt_eq hp i k,
      angle_positive_smul_signedRay
        (rayRhoAt_pos hp i j)
        (rayRhoAt_pos hp i k)]
  rw [angle_signedRayDirection_eq_pi_sub_of_sign_ne
      hsign]
  · rw [habs]
  · rw [habs]
    exact hbounds.2

/-- Sendov-normalized ordinary form. -/
theorem actual_angle_eq_pi_sub_s_mul_lam_of_ordinary_transition
    {V : Type*} {p : V → Plane}
    (hp : Function.Injective p)
    {t lam s : ℝ}
    (ht : 0 < t)
    (hlam : lam = Real.pi / t)
    (i : V)
    {j k : OtherVertex i}
    (horder : rayThetaAt hp i j ≤ rayThetaAt hp i k)
    (hsign : raySignAt hp i j ≠ raySignAt hp i k)
    (hs :
      s =
        t * ((rayThetaAt hp i k -
          rayThetaAt hp i j) / Real.pi)) :
    EuclideanGeometry.angle (p j.1) (p i) (p k.1) =
      Real.pi - s * lam := by
  rw [actual_angle_eq_pi_sub_ordinary_gap_of_sign_ne
      hp i horder hsign]
  rw [hs, hlam]
  field_simp [ne_of_gt ht, Real.pi_ne_zero]
  ring

/-- Exact actual angle across a lifted cyclic-wrap sign transition. -/
theorem actual_angle_eq_pi_sub_wrap_gap_of_lifted_sign_ne
    {V : Type*} {p : V → Plane}
    (hp : Function.Injective p)
    (i : V)
    {first last : OtherVertex i}
    (horder :
      rayThetaAt hp i first ≤ rayThetaAt hp i last)
    (hsign :
      raySignAt hp i last ≠ !raySignAt hp i first) :
    EuclideanGeometry.angle (p last.1) (p i) (p first.1) =
      Real.pi -
        (rayThetaAt hp i first + Real.pi -
          rayThetaAt hp i last) := by
  have hgap0 :
      0 ≤ rayThetaAt hp i first + Real.pi -
        rayThetaAt hp i last := by
    have hf0 := rayThetaAt_nonneg hp i first
    have hlpi := rayThetaAt_lt_pi hp i last
    linarith
  have hgapPi :
      rayThetaAt hp i first + Real.pi -
        rayThetaAt hp i last ≤ Real.pi := by
    linarith
  have hfirstShift :
      p first.1 - p i =
        rayRhoAt hp i first •
          signedRayDirection (!raySignAt hp i first)
            (rayThetaAt hp i first + Real.pi) := by
    rw [rayRepAt_eq hp i first]
    exact same_ray_after_pi_shift_to_common_sign
      (raySignAt hp i first)
      (rayThetaAt hp i first)
  change
    InnerProductGeometry.angle
        (p last.1 - p i) (p first.1 - p i) =
      Real.pi -
        (rayThetaAt hp i first + Real.pi -
          rayThetaAt hp i last)
  rw [rayRepAt_eq hp i last, hfirstShift,
      angle_positive_smul_signedRay
        (rayRhoAt_pos hp i last)
        (rayRhoAt_pos hp i first)]
  have htheta :
      rayThetaAt hp i last ≤
        rayThetaAt hp i first + Real.pi := by
    linarith
  have habs :
      |rayThetaAt hp i last -
          (rayThetaAt hp i first + Real.pi)| =
        rayThetaAt hp i first + Real.pi -
          rayThetaAt hp i last := by
    rw [abs_of_nonpos]
    · ring
    · linarith
  rw [angle_signedRayDirection_eq_pi_sub_of_sign_ne
      hsign]
  · rw [habs]
  · rw [habs]
    exact hgapPi

/-- Sendov-normalized cyclic-wrap form. -/
theorem actual_angle_eq_pi_sub_s_mul_lam_of_wrap_transition
    {V : Type*} {p : V → Plane}
    (hp : Function.Injective p)
    {t lam s : ℝ}
    (ht : 0 < t)
    (hlam : lam = Real.pi / t)
    (i : V)
    {first last : OtherVertex i}
    (horder :
      rayThetaAt hp i first ≤ rayThetaAt hp i last)
    (hsign :
      raySignAt hp i last ≠ !raySignAt hp i first)
    (hs :
      s =
        t * ((rayThetaAt hp i first + Real.pi -
          rayThetaAt hp i last) / Real.pi)) :
    EuclideanGeometry.angle (p last.1) (p i) (p first.1) =
      Real.pi - s * lam := by
  rw [actual_angle_eq_pi_sub_wrap_gap_of_lifted_sign_ne
      hp i horder hsign]
  rw [hs, hlam]
  field_simp [ne_of_gt ht, Real.pi_ne_zero]
  ring

/-- Physical bad-width identity for an ordinary critical transition. -/
theorem ordinary_critical_bad_width_eq_angle_excess
    {V : Type*} {p : V → Plane}
    (hp : Function.Injective p)
    {t lam delta s : ℝ} {n : ℕ}
    (ht : 0 < t)
    (htSendov : t = (n : ℝ) + delta)
    (hlam : lam = Real.pi / t)
    (i : V)
    {j k : OtherVertex i}
    (horder : rayThetaAt hp i j ≤ rayThetaAt hp i k)
    (hsign : raySignAt hp i j ≠ raySignAt hp i k)
    (hs :
      s =
        t * ((rayThetaAt hp i k -
          rayThetaAt hp i j) / Real.pi)) :
    lam * criticalBadWidth delta s =
      EuclideanGeometry.angle (p j.1) (p i) (p k.1) -
        ((n : ℝ) - 1) * lam := by
  have hpi : Real.pi = ((n : ℝ) + delta) * lam := by
    rw [← htSendov, hlam]
    field_simp [ne_of_gt ht]
  have hangle :=
    actual_angle_eq_pi_sub_s_mul_lam_of_ordinary_transition
      hp ht hlam i horder hsign hs
  exact critical_bad_width_mul_eq_angle_excess
    hpi hangle

/-- Physical bad-width identity for a cyclic-wrap critical transition. -/
theorem wrap_critical_bad_width_eq_angle_excess
    {V : Type*} {p : V → Plane}
    (hp : Function.Injective p)
    {t lam delta s : ℝ} {n : ℕ}
    (ht : 0 < t)
    (htSendov : t = (n : ℝ) + delta)
    (hlam : lam = Real.pi / t)
    (i : V)
    {first last : OtherVertex i}
    (horder :
      rayThetaAt hp i first ≤ rayThetaAt hp i last)
    (hsign :
      raySignAt hp i last ≠ !raySignAt hp i first)
    (hs :
      s =
        t * ((rayThetaAt hp i first + Real.pi -
          rayThetaAt hp i last) / Real.pi)) :
    lam * criticalBadWidth delta s =
      EuclideanGeometry.angle (p last.1) (p i) (p first.1) -
        ((n : ℝ) - 1) * lam := by
  have hpi : Real.pi = ((n : ℝ) + delta) * lam := by
    rw [← htSendov, hlam]
    field_simp [ne_of_gt ht]
  have hangle :=
    actual_angle_eq_pi_sub_s_mul_lam_of_wrap_transition
      hp ht hlam i horder hsign hs
  exact critical_bad_width_mul_eq_angle_excess
    hpi hangle

#print axioms actual_angle_eq_pi_sub_ordinary_gap_of_sign_ne
#print axioms actual_angle_eq_pi_sub_s_mul_lam_of_ordinary_transition
#print axioms actual_angle_eq_pi_sub_wrap_gap_of_lifted_sign_ne
#print axioms actual_angle_eq_pi_sub_s_mul_lam_of_wrap_transition
#print axioms ordinary_critical_bad_width_eq_angle_excess
#print axioms wrap_critical_bad_width_eq_angle_excess

end JSP000404Research
