import JSP000404Research.WrapObstructionWidth
import Mathlib.Tactic

/-!
# Critical transition gaps and their bad-phase intervals

Work on one real lift of the normalized projective direction circle.

A critical adjacent sign-transition gap has endpoints

  alpha < alpha + s

with

  1 <= s <= 1 + delta.

A wrap arc has normalized length 1+delta.  The phases for which the wrap arc
can bridge across this critical gap form the interval

  [alpha + s - 1, alpha + delta].

Its length is

  (alpha + delta) - (alpha + s - 1)
    = 1 + delta - s,

hence lies in [0,delta].  More importantly, the bad-phase interval itself is
contained in the generating critical gap [alpha, alpha+s].

When s=1 (the exact maximum-angle case) the obstruction has maximal width
delta and is exactly [alpha, alpha+delta].
-/

namespace JSP000404Research

/-- Left endpoint of the bad-phase interval generated by a critical gap. -/
def criticalBadLeft (alpha s : ℝ) : ℝ :=
  alpha + s - 1

/-- Right endpoint of the bad-phase interval generated by a critical gap. -/
def criticalBadRight (alpha delta : ℝ) : ℝ :=
  alpha + delta

/-- Exact bad-interval width. -/
theorem critical_bad_width
    (alpha s delta : ℝ) :
    criticalBadRight alpha delta - criticalBadLeft alpha s =
      1 + delta - s := by
  simp [criticalBadLeft, criticalBadRight]
  ring

/-- A critical gap produces a nonempty bad interval of width at most delta. -/
theorem critical_bad_width_bounds
    {alpha s delta : ℝ}
    (hdelta0 : 0 ≤ delta)
    (hs1 : 1 ≤ s)
    (hsTop : s ≤ 1 + delta) :
    0 ≤ criticalBadRight alpha delta - criticalBadLeft alpha s ∧
      criticalBadRight alpha delta - criticalBadLeft alpha s ≤ delta := by
  rw [critical_bad_width]
  constructor <;> linarith

/-- The bad interval begins inside the generating critical gap. -/
theorem critical_bad_left_in_gap
    {alpha s : ℝ}
    (hs1 : 1 ≤ s) :
    alpha ≤ criticalBadLeft alpha s ∧
      criticalBadLeft alpha s ≤ alpha + s := by
  simp [criticalBadLeft]
  constructor <;> linarith

/-- In the lower branch delta<1, the bad interval ends strictly before the
right endpoint of every critical gap of length at least one. -/
theorem critical_bad_right_in_gap
    {alpha s delta : ℝ}
    (hdelta0 : 0 ≤ delta)
    (hdelta1 : delta < 1)
    (hs1 : 1 ≤ s) :
    alpha ≤ criticalBadRight alpha delta ∧
      criticalBadRight alpha delta < alpha + s := by
  simp [criticalBadRight]
  constructor <;> linarith

/-- Hence the full bad-phase interval is contained in its generating gap. -/
theorem critical_bad_interval_nested
    {alpha s delta x : ℝ}
    (hdelta0 : 0 ≤ delta)
    (hdelta1 : delta < 1)
    (hs1 : 1 ≤ s)
    (hx :
      criticalBadLeft alpha s ≤ x ∧
      x ≤ criticalBadRight alpha delta) :
    alpha ≤ x ∧ x < alpha + s := by
  have hl := critical_bad_left_in_gap (alpha := alpha) hs1
  have hr :=
    critical_bad_right_in_gap
      (alpha := alpha) (s := s) hdelta0 hdelta1 hs1
  constructor
  · exact hl.1.trans hx.1
  · exact hx.2.trans_lt hr.2

/-- Exact maximum-angle critical gaps s=1 produce the maximal delta-width
obstruction [alpha, alpha+delta]. -/
theorem critical_bad_of_unit_gap
    (alpha delta : ℝ) :
    criticalBadLeft alpha 1 = alpha ∧
      criticalBadRight alpha delta = alpha + delta ∧
      criticalBadRight alpha delta - criticalBadLeft alpha 1 = delta := by
  simp [criticalBadLeft, criticalBadRight]

/-- Conversely, under the critical lower bound s>=1, attaining the full
delta obstruction width forces s=1. -/
theorem critical_bad_full_width_iff
    {alpha s delta : ℝ}
    (hs1 : 1 ≤ s) :
    criticalBadRight alpha delta - criticalBadLeft alpha s = delta ↔
      s = 1 := by
  rw [critical_bad_width]
  constructor <;> intro h <;> linarith

#print axioms critical_bad_width
#print axioms critical_bad_width_bounds
#print axioms critical_bad_interval_nested
#print axioms critical_bad_of_unit_gap
#print axioms critical_bad_full_width_iff

end JSP000404Research
