
import JSP000404Research.ProjectionPolarReconstruction
import JSP000404Research.PlanarDirectionBridge
import Mathlib.Tactic

/-!
# Generic projection produces a complete ForwardAngleLift

For a finite injective planar configuration, use the explicit generic
projection order from ProjectionOrderedVertices.

ProjectionHalfPlaneAngle supplies one common angular branch of width pi.
ProjectionPolarReconstruction supplies positive radii and exact edge
representations. ProjectionAngleBetweenness supplies the triangle direction
betweenness axiom.

Together these data form a complete ForwardAngleLift.

Combining with PlanarDirectionBridge then gives the ordered DirectionData used
by the residual/band proof directly from the original planar AngleCap.
-/

namespace JSP000404Research

open Real

namespace ProjectionOrdered

/-- Angle cap is invariant under the projection-order reindexing. -/
theorem angleCap_reindexed
    {V : Type*}
    {p : V → Plane} {lam : ℝ}
    (hcap : AngleCap p lam) :
    AngleCap (reindexedPoint p) lam := by
  intro a b c hab hac hbc
  have hab' :
      a.toOriginal ≠ b.toOriginal := by
    intro h
    exact hab (toOriginal_injective h)
  have hac' :
      a.toOriginal ≠ c.toOriginal := by
    intro h
    exact hac (toOriginal_injective h)
  have hbc' :
      b.toOriginal ≠ c.toOriginal := by
    intro h
    exact hbc (toOriginal_injective h)
  exact hcap
    a.toOriginal b.toOriginal c.toOriginal
    hab' hac' hbc'

/-- Complete coherent forward angular lift generated by the generic
projection. -/
noncomputable def genericForwardAngleLift
    {V : Type*} [Fintype V]
    {p : V → Plane}
    (hp : Function.Injective p) :
    @ForwardAngleLift
      (ProjectionOrdered V)
      (projectionLinearOrder hp)
      (reindexedPoint p)
      (projectionAngleBase (genericProjectionSlope p)) := by
  letI : LinearOrder (ProjectionOrdered V) :=
    projectionLinearOrder hp
  let a : ℝ := genericProjectionSlope p
  refine
    { theta := fun i j =>
        projectionLiftedAngle a
          (p j.toOriginal - p i.toOriginal)
      rho := fun i j =>
        projectionLiftedRho a
          (p j.toOriginal - p i.toOriginal)
      rho_pos := ?_
      theta_lower := ?_
      theta_upper := ?_
      repr := ?_
      between := ?_ }
  · intro i j hij
    exact generic_edge_liftedRho_pos hp hij
  · intro i j hij
    have h :=
      generic_edge_liftedAngle_mem hp hij
    exact h.1.le
  · intro i j hij
    exact (generic_edge_liftedAngle_mem hp hij).2
  · intro i j hij
    change
      p j.toOriginal - p i.toOriginal =
        projectionLiftedRho a
            (p j.toOriginal - p i.toOriginal) •
          rayDirection
            (projectionLiftedAngle a
              (p j.toOriginal - p i.toOriginal))
    exact projection_polar_repr
      a (p j.toOriginal - p i.toOriginal)
  · intro i j k hij hjk
    exact generic_projection_liftedAngle_between
      hp hij hjk

/-- Full planar-to-DirectionData bridge in Sendov normalization. -/
noncomputable def genericDirectionData_sendov
    {V : Type*} [Fintype V]
    {p : V → Plane}
    (hp : Function.Injective p)
    {lam t : ℝ}
    (hcap : AngleCap p lam)
    (ht : 0 < t)
    (hlam : lam = Real.pi / t) :
    @DirectionData
      (ProjectionOrdered V)
      (projectionLinearOrder hp)
      t := by
  letI : LinearOrder (ProjectionOrdered V) :=
    projectionLinearOrder hp
  exact
    (genericForwardAngleLift hp).toDirectionData_sendov
      (angleCap_reindexed hcap) ht hlam

/-- The resulting direction value is the normalized lifted generic-projection
angle. -/
theorem genericDirectionData_sendov_value
    {V : Type*} [Fintype V]
    {p : V → Plane}
    (hp : Function.Injective p)
    {lam t : ℝ}
    (hcap : AngleCap p lam)
    (ht : 0 < t)
    (hlam : lam = Real.pi / t)
    (i j : ProjectionOrdered V) :
    (genericDirectionData_sendov
      hp hcap ht hlam).value i j
      =
    (projectionLiftedAngle
        (genericProjectionSlope p)
        (p j.toOriginal - p i.toOriginal)
      -
      projectionAngleBase (genericProjectionSlope p)) / lam := by
  rfl

#print axioms angleCap_reindexed
#print axioms genericForwardAngleLift
#print axioms genericDirectionData_sendov
#print axioms genericDirectionData_sendov_value

end ProjectionOrdered
end JSP000404Research
