
import JSP000404Research.ProjectionStandardBandBudget
import JSP000404Research.ResidualHardRemainder
import Mathlib.Tactic

/-!
# Concrete planar reduction to the residual hard-word inequality

The generic-projection bridge now provides the actual standard residual
colouring of a planar Sendov configuration, and ProjectionStandardBandBudget
proves the exact one-layer active-colour hypothesis for the genuine centre
exponent.

Therefore ResidualHardRemainder can be instantiated directly.

For lower-branch normalization

  t = n + delta,   0 <= delta < 1,

let B be the standard (n+1)-band colouring generated by the generic projection
and let

  k(i) = centreExponent(C_i,t).

Then

  k(i) < n,
  card(active_B(i)) <= n-k(i)+1.

Hence the centre-level target

  sum_i 2^k(i) <= 2^n

follows from one concrete finite Boolean statement only:

  card(saturatedOverlapWords(B,k))
    + card(lossCompletionWords(B,k))
      <=
  2^n - card(coveredCompletionWords(B)).

No representation bridge, phase-majorization statement, or comb-profile
hypothesis remains hidden in this reduction.
-/

namespace JSP000404Research
namespace ProjectionOrdered

open OrderedEdgeColoring
open DirectionData
open scoped BigOperators

noncomputable def genericResidualColoring
    {V : Type*} [Fintype V]
    {p : V → Plane}
    (hp : Function.Injective p)
    {lam t : ℝ}
    (hcap : AngleCap p lam)
    (htPos : 0 < t)
    (hlam : lam = Real.pi / t)
    (n : ℕ)
    (hwidth : t < (n : ℝ) + 1) :
    @OrderedEdgeColoring
      (ProjectionOrdered V)
      (projectionLinearOrder hp)
      (n + 1) := by
  letI : LinearOrder (ProjectionOrdered V) :=
    projectionLinearOrder hp
  exact standardResidualColoring
    (genericDirectionData_sendov hp hcap htPos hlam)
    n hwidth

/-- Concrete hard-word reduction for the planar lower branch. -/
theorem genericProjection_exponent_capacity_of_hard_words_fit_holes
    {V : Type*} [Fintype V]
    {p : V → Plane}
    (hp : Function.Injective p)
    {lam t delta : ℝ} {n : ℕ}
    (hcap : AngleCap p lam)
    (hn : 1 ≤ n)
    (hdelta0 : 0 ≤ delta)
    (hdelta1 : delta < 1)
    (htEq : t = (n : ℝ) + delta)
    (hlam : lam = Real.pi / t)
    (C :
      ∀ i : ProjectionOrdered V,
        CentreProjectiveCycle (reindexedPoint_injective hp) i)
    (hholes :
      let B :=
        genericResidualColoring
          hp hcap
          (sendov_scale_pos hn hdelta0 htEq)
          hlam n
          (by
            rw [htEq]
            linarith)
      let exponent :=
        fun i : ProjectionOrdered V =>
          centreExponent (C i) t
      (saturatedOverlapWords B exponent).card +
          (lossCompletionWords B exponent).card
        ≤
      2 ^ n - (coveredCompletionWords B).card) :
    ∑ i : ProjectionOrdered V,
        2 ^ centreExponent (C i) t
      ≤
    2 ^ n := by
  letI : LinearOrder (ProjectionOrdered V) :=
    projectionLinearOrder hp
  have htPos :
      0 < t :=
    sendov_scale_pos hn hdelta0 htEq
  have hwidth :
      t < (n : ℝ) + 1 := by
    rw [htEq]
    linarith
  let B : OrderedEdgeColoring (ProjectionOrdered V) (n + 1) :=
    genericResidualColoring
      hp hcap htPos hlam n hwidth
  let exponent : ProjectionOrdered V → ℕ :=
    fun i => centreExponent (C i) t
  have hprofile :=
    genericProjection_lowerBranch_profile_hypotheses
      hp hcap hn hdelta0 hdelta1 htEq hlam C
  have hexp :
      ∀ i, exponent i ≤ n := by
    intro i
    exact Nat.le_of_lt (hprofile.1 i)
  have honeLoss :
      ∀ i,
        (active B i).card ≤
          n - exponent i + 1 := by
    intro i
    simpa [B, genericResidualColoring, exponent]
      using hprofile.2 i
  have hholes' :
      (saturatedOverlapWords B exponent).card +
          (lossCompletionWords B exponent).card
        ≤
      2 ^ n - (coveredCompletionWords B).card := by
    simpa [B, exponent, genericResidualColoring] using hholes
  have hcapCentre :=
    exponent_capacity_of_hard_words_fit_holes
      B exponent hexp honeLoss hholes'
  simpa [exponent] using hcapCentre

#print axioms genericResidualColoring
#print axioms genericProjection_exponent_capacity_of_hard_words_fit_holes

end ProjectionOrdered
end JSP000404Research
