import JSP000404Research.ResidualReducedZeroFullRematchQuotient
import Mathlib.Logic.Relation
import Mathlib.Tactic

/-!
# Translation quotient for reduced-zero overlap cubes

A lossless equal-dimension reduced-zero rematch does not create a genuinely
new Boolean overlap shape: the new pair intersection is the image of the old
intersection under one coordinate flip.

This file turns that observation into an actual quotient state.

* oneFlipOverlapRel is the elementary relation generated by one coordinate
  flip on a finite overlap-word set;
* OverlapTranslationEquivalent is its equivalence closure;
* OverlapTranslationQuotient is the resulting quotient;
* an equal-dimension full-blocker rematch lands in exactly the same quotient
  state;
* therefore every distinct two-full-blocker rematch is either strict progress
  in common-inactive dimension or stationary in the translation quotient.

No recursion theorem is claimed here. The point is to expose the precise
state quotient needed by the reduced-zero recursive frontier.
-/

namespace JSP000404Research
namespace OrderedEdgeColoring

def oneFlipOverlapRel
    {n : ℕ}
    (S T : Finset (Fin n → Bool)) : Prop :=
  ∃ c : Fin n,
    S.image (fun word => flipBoolWordAt word c) = T

def OverlapTranslationEquivalent
    {n : ℕ}
    (S T : Finset (Fin n → Bool)) : Prop :=
  Relation.EqvGen (@oneFlipOverlapRel n) S T

def overlapTranslationSetoid
    (n : ℕ) :
    Setoid (Finset (Fin n → Bool)) :=
  Relation.EqvGen.setoid (@oneFlipOverlapRel n)

abbrev OverlapTranslationQuotient
    (n : ℕ) :=
  Quotient (overlapTranslationSetoid n)

theorem oneFlipOverlapRel_step
    {n : ℕ}
    (S : Finset (Fin n → Bool))
    (c : Fin n) :
    oneFlipOverlapRel
      S
      (S.image (fun word => flipBoolWordAt word c)) :=
  ⟨c,rfl⟩

theorem oneFlipOverlap_translation_equivalent
    {n : ℕ}
    (S : Finset (Fin n → Bool))
    (c : Fin n) :
    OverlapTranslationEquivalent
      S
      (S.image (fun word => flipBoolWordAt word c)) := by
  exact Relation.EqvGen.rel _ _
    (oneFlipOverlapRel_step S c)

theorem oneFlipOverlap_same_quotient
    {n : ℕ}
    (S : Finset (Fin n → Bool))
    (c : Fin n) :
    Quotient.mk
        (overlapTranslationSetoid n) S
      =
    Quotient.mk
        (overlapTranslationSetoid n)
        (S.image (fun word => flipBoolWordAt word c)) := by
  apply Quotient.sound
  exact oneFlipOverlap_translation_equivalent S c

theorem oneFlip_fullBlocker_pair_same_overlap_quotient_of_commonInactive_card_eq
    {V : Type*} [LinearOrder V] [Fintype V] {n : ℕ}
    (C : OrderedEdgeColoring V (n + 1))
    {u v w z : V} {c : Fin n}
    {base : Fin n → Bool}
    (hbase :
      base ∈ retainedCompletionWords C u ∩
        retainedCompletionWords C v)
    (hw : w ∈ oneFlipFullBlockers C u v c)
    (hz : z ∈ oneFlipFullBlockers C u v c)
    (hdim :
      (commonInactiveRetained C w z).card =
        (commonInactiveRetained C u v).card) :
    Quotient.mk
        (overlapTranslationSetoid n)
        (retainedCompletionWords C u ∩
          retainedCompletionWords C v)
      =
    Quotient.mk
        (overlapTranslationSetoid n)
        (retainedCompletionWords C w ∩
          retainedCompletionWords C z) := by
  have hset :=
    oneFlip_fullBlocker_pair_intersection_eq_image_of_commonInactive_card_eq
      C hbase hw hz hdim
  calc
    Quotient.mk
        (overlapTranslationSetoid n)
        (retainedCompletionWords C u ∩
          retainedCompletionWords C v)
      =
    Quotient.mk
        (overlapTranslationSetoid n)
        ((retainedCompletionWords C u ∩
            retainedCompletionWords C v).image
          (fun word => flipBoolWordAt word c)) :=
      oneFlipOverlap_same_quotient
        (retainedCompletionWords C u ∩
          retainedCompletionWords C v) c
    _ =
    Quotient.mk
        (overlapTranslationSetoid n)
        (retainedCompletionWords C w ∩
          retainedCompletionWords C z) := by
      rw [hset]

theorem oneFlip_two_fullBlockers_dimension_strict_or_same_overlap_quotient
    {V : Type*} [LinearOrder V] [Fintype V] {n : ℕ}
    (C : OrderedEdgeColoring V (n + 1))
    {u v w z : V} {c : Fin n}
    {base : Fin n → Bool}
    (hbase :
      base ∈ retainedCompletionWords C u ∩
        retainedCompletionWords C v)
    (hcu : c ∈ retainedActive C u)
    (hw : w ∈ oneFlipFullBlockers C u v c)
    (hz : z ∈ oneFlipFullBlockers C u v c)
    (hwz : w ≠ z) :
    (commonInactiveRetained C u v).card <
        (commonInactiveRetained C w z).card
    ∨
    Quotient.mk
        (overlapTranslationSetoid n)
        (retainedCompletionWords C u ∩
          retainedCompletionWords C v)
      =
    Quotient.mk
        (overlapTranslationSetoid n)
        (retainedCompletionWords C w ∩
          retainedCompletionWords C z) := by
  rcases
      oneFlip_two_fullBlockers_dimension_strict_or_translated_quotient
        C hbase hcu hw hz hwz
    with hdim | htranslate
  · exact Or.inl hdim
  · right
    apply Quotient.sound
    exact Relation.EqvGen.rel _ _
      ⟨c,htranslate⟩

#print axioms oneFlipOverlap_same_quotient
#print axioms
  oneFlip_fullBlocker_pair_same_overlap_quotient_of_commonInactive_card_eq
#print axioms
  oneFlip_two_fullBlockers_dimension_strict_or_same_overlap_quotient

end OrderedEdgeColoring
end JSP000404Research
