import JSP000404Research.ResidualWholeCubePairSharedMass
import JSP000404Research.ResidualLossAllActiveSlices
import Mathlib.Tactic

/-!
# Two-flip completion cubes generated by a whole-cube Q/T pair

Fix a source completion cube Q_v and two active coordinates c,d.
Define the two-flip cube by applying both bit flips to Q_v.

If (s,v,c) is a WholeCubeQTPair, then Q_s = T_c(v), so translating Q_s
along d gives exactly the two-flip cube of Q_v at {c,d}.

This is the algebraic normalization needed to collapse the six second-order
translated slices of three whole-cube partners into only three unordered
two-coordinate cubes.
-/

namespace JSP000404Research
namespace OrderedEdgeColoring

noncomputable def twoFlipCompletionWords
    {V : Type*} [LinearOrder V] {n : ℕ}
    (C : OrderedEdgeColoring V (n + 1))
    (v : V) (c d : Fin n) : Finset (Fin n → Bool) :=
  (retainedCompletionWords C v).image
    (fun word => flipBoolWordAt (flipBoolWordAt word c) d)

theorem twoFlipCompletionWords_card
    {V : Type*} [LinearOrder V] {n : ℕ}
    (C : OrderedEdgeColoring V (n + 1))
    (v : V) (c d : Fin n) :
    (twoFlipCompletionWords C v c d).card =
      (retainedCompletionWords C v).card := by
  unfold twoFlipCompletionWords
  rw [Finset.card_image_iff.mpr]
  intro a ha b hb hab
  apply two_flip_injective c d hab

theorem twoFlipCompletionWords_comm
    {V : Type*} [LinearOrder V] {n : ℕ}
    (C : OrderedEdgeColoring V (n + 1))
    (v : V) {c d : Fin n}
    (hcd : c ≠ d) :
    twoFlipCompletionWords C v c d =
      twoFlipCompletionWords C v d c := by
  classical
  ext word
  constructor
  · intro hw
    obtain ⟨base,hbase,rfl⟩ := Finset.mem_image.mp hw
    apply Finset.mem_image.mpr
    refine ⟨base,hbase,?_⟩
    exact flipBoolWordAt_commute base hcd
  · intro hw
    obtain ⟨base,hbase,rfl⟩ := Finset.mem_image.mp hw
    apply Finset.mem_image.mpr
    refine ⟨base,hbase,?_⟩
    exact (flipBoolWordAt_commute base hcd).symm

theorem wholeCubeQTPair_partner_translated_eq_twoFlip
    {V : Type*} [LinearOrder V] {n : ℕ}
    (C : OrderedEdgeColoring V (n + 1))
    {s v : V} {c d : Fin n}
    (hcV : c ∈ retainedActive C v)
    (hdV : d ∈ retainedActive C v)
    (hcd : c ≠ d)
    (hwhole : WholeCubeQTPair C s v c) :
    translatedCompletionWords C s d =
      twoFlipCompletionWords C v c d := by
  classical
  rcases hwhole with ⟨hactiveEq,htransEq⟩
  have hdS : d ∈ retainedActive C s := by
    rw [← hactiveEq]
    exact hdV
  ext word
  constructor
  · intro hword
    have hbaseS :
        flipBoolWordAt word d ∈ retainedCompletionWords C s :=
      (mem_translatedCompletionWords C s d word).1 hword
    have hbaseTc :
        flipBoolWordAt word d ∈ translatedCompletionWords C v c := by
      rw [htransEq]
      exact hbaseS
    have hbaseV :
        flipBoolWordAt (flipBoolWordAt word d) c ∈
          retainedCompletionWords C v :=
      (mem_translatedCompletionWords C v c
        (flipBoolWordAt word d)).1 hbaseTc
    apply Finset.mem_image.mpr
    refine ⟨flipBoolWordAt (flipBoolWordAt word d) c,
      hbaseV,?_⟩
    rw [flipBoolWordAt_commute word hcd.symm]
    simp [flipBoolWordAt_involutive]
  · intro hword
    obtain ⟨base,hbase,hwordEq⟩ :=
      Finset.mem_image.mp hword
    have hdS' : d ∈ retainedActive C s := hdS
    apply (mem_translatedCompletionWords C s d word).2
    rw [← htransEq]
    apply (mem_translatedCompletionWords C v c
      (flipBoolWordAt word d)).2
    rw [← hwordEq]
    rw [flipBoolWordAt_commute base hcd]
    simp [flipBoolWordAt_involutive]
    exact hbase

#print axioms twoFlipCompletionWords_card
#print axioms twoFlipCompletionWords_comm
#print axioms wholeCubeQTPair_partner_translated_eq_twoFlip

end OrderedEdgeColoring
end JSP000404Research
