import JSP000404Research.MinimalPhaseCover
import JSP000404Research.PhaseArithmetic
import JSP000404Research.CriticalPhaseInterval
import JSP000404Research.GlobalProjectiveDirectionCount
import Mathlib.Tactic

/-!
# Six-point critical phase covers need more direction slots than exist

A critical bad interval generated by a projective transition gap is

  [alpha + s - 1, alpha + delta].

Its right endpoint depends only on alpha.  Therefore two critical intervals
with the same generating left projective direction alpha are automatically
nested: compare s to order the left endpoints while the right endpoints agree.

An inclusion-irredundant interval cover can contain at most one interval from
each nested slot.  For a six-point configuration there are at most 15 global
projective edge directions, hence at most 15 selected critical intervals.

But when n>=7 and 0<=delta<1/2, any delta-width cover of a phase circle of
length n+delta needs at least 2n+2 >= 16 intervals.

Thus no such critical cover exists.  The remaining geometric bridge is only
to show that every bad phase is dominated by one of these critical
transition-gap intervals.
-/

namespace JSP000404Research

/-- Critical intervals sharing the same alpha are nested. -/
theorem critical_intervals_nested_of_same_alpha
    {I Slot : Type*}
    (alpha : Slot → ℝ)
    (s : I → ℝ)
    (slot : I → Slot)
    (delta : ℝ)
    {i j : I}
    (hslot : slot i = slot j) :
    let L : I → ℝ :=
      fun k => criticalBadLeft (alpha (slot k)) (s k)
    let R : I → ℝ :=
      fun k => criticalBadRight (alpha (slot k)) delta
    (L i ≤ L j ∧ R j ≤ R i) ∨
      (L j ≤ L i ∧ R i ≤ R j) := by
  dsimp
  have hR :
      criticalBadRight (alpha (slot i)) delta =
        criticalBadRight (alpha (slot j)) delta := by
    rw [hslot]
  rcases le_total (s i) (s j) with hij | hji
  · left
    constructor
    · simp [criticalBadLeft]
      rw [hslot]
      linarith
    · exact hR.symm.le
  · right
    constructor
    · simp [criticalBadLeft]
      rw [← hslot]
      linarith
    · exact hR.le

/-- Pure finite-slot terminal: fifteen nested critical slots cannot cover the
lower-branch phase circle once n>=7. -/
theorem no_critical_phase_cover_of_at_most_fifteen_slots
    {I Slot : Type*}
    [DecidableEq I] [Fintype Slot]
    (alpha : Slot → ℝ)
    (s : I → ℝ)
    (slot : I → Slot)
    (S : Finset I)
    (n : ℕ) (delta : ℝ)
    (hn : 7 ≤ n)
    (hdelta0 : 0 ≤ delta)
    (hdeltaHalf : delta < (1 : ℝ) / 2)
    (hslotCard : Fintype.card Slot ≤ 15)
    (hcoverLower :
      ∀ T : Finset I, T ⊆ S →
        PredicateCovers
          (InClosedInterval
            (fun k => criticalBadLeft
              (alpha (slot k)) (s k))
            (fun k => criticalBadRight
              (alpha (slot k)) delta))
          T →
        (n : ℝ) + delta ≤ (T.card : ℝ) * delta) :
    ¬ PredicateCovers
      (InClosedInterval
        (fun k => criticalBadLeft
          (alpha (slot k)) (s k))
        (fun k => criticalBadRight
          (alpha (slot k)) delta))
      S := by
  intro hcover
  let L : I → ℝ :=
    fun k => criticalBadLeft (alpha (slot k)) (s k)
  let R : I → ℝ :=
    fun k => criticalBadRight (alpha (slot k)) delta
  obtain ⟨T, hTS, hmin⟩ :=
    exists_irredundant_subcover
      (InClosedInterval L R) S hcover
  have hnested :
      ∀ {i j : I}, slot i = slot j →
        (L i ≤ L j ∧ R j ≤ R i) ∨
        (L j ≤ L i ∧ R i ≤ R j) := by
    intro i j hij
    exact critical_intervals_nested_of_same_alpha
      alpha s slot delta hij
  have hcardSlot :
      T.card ≤ Fintype.card Slot :=
    irredundant_card_le_slots_of_nested_fibres
      L R slot T hmin hnested
  have hcard15 : T.card ≤ 15 :=
    hcardSlot.trans hslotCard
  have hcoverReal :
      (n : ℝ) + delta ≤ (T.card : ℝ) * delta := by
    exact hcoverLower T hTS hmin.1
  have hneed :
      2 * n + 2 ≤ T.card :=
    phase_cover_count_lower
      (by omega) hdelta0 hdeltaHalf hcoverReal
  omega

/-- Six-point specialization with slots equal to actual global projective edge
directions. -/
theorem no_six_point_critical_phase_cover_by_edge_directions
    {V I : Type*} [Fintype V] [DecidableEq I]
    {p : V → Plane}
    (hp : Function.Injective p)
    (hcard : Fintype.card V = 6)
    (s : I → ℝ)
    (slot :
      I → {theta : ℝ // theta ∈ projectiveEdgeDirections hp})
    (S : Finset I)
    (n : ℕ) (delta : ℝ)
    (hn : 7 ≤ n)
    (hdelta0 : 0 ≤ delta)
    (hdeltaHalf : delta < (1 : ℝ) / 2)
    (hcoverLower :
      ∀ T : Finset I, T ⊆ S →
        PredicateCovers
          (InClosedInterval
            (fun k => criticalBadLeft
              (slot k).1 (s k))
            (fun k => criticalBadRight
              (slot k).1 delta))
          T →
        (n : ℝ) + delta ≤ (T.card : ℝ) * delta) :
    ¬ PredicateCovers
      (InClosedInterval
        (fun k => criticalBadLeft
          (slot k).1 (s k))
        (fun k => criticalBadRight
          (slot k).1 delta))
      S := by
  classical
  apply no_critical_phase_cover_of_at_most_fifteen_slots
      (fun theta :
        {theta : ℝ // theta ∈ projectiveEdgeDirections hp} =>
          theta.1)
      s slot S n delta
      hn hdelta0 hdeltaHalf
  · simpa [Fintype.card_coe] using
      projectiveEdgeDirections_card_le_fifteen_of_card_six
        hp hcard
  · exact hcoverLower

#print axioms critical_intervals_nested_of_same_alpha
#print axioms no_critical_phase_cover_of_at_most_fifteen_slots
#print axioms no_six_point_critical_phase_cover_by_edge_directions

end JSP000404Research
