import JSP000404Research.StrictExposure
import Mathlib.Tactic

/-!
# Strict support cones behind exposed centres

A strict supporting vector at centre i is a vector u satisfying

  0 < inner u (p j - p i)

for every other vertex j.

If all displacement rays from i share one signed projective orientation and
their parameters lie in [a,a+width] with width<pi, then not only the midpoint
but every parameter

  phi in (a+width-pi/2, a+pi/2)

is a strict supporting direction.  This open dual interval has exact angular
length pi-width.

For a transition split, pi-width is exactly the transition projective gap.
Thus every one-support transition gap produces an open arc of strict support
directions of the same angular size.

Different vertices cannot share a strict supporting vector.  Consequently the
remaining global geometry is a circle-packing statement for these support arcs.
-/

namespace JSP000404Research

open Real

/-- A fixed vector strictly exposes a point. -/
def StrictSupportsAt
    {V : Type*} (p : V → Plane) (i : V) (u : Plane) : Prop :=
  ∀ j, j ≠ i → 0 < inner ℝ u (p j - p i)

theorem strictlyExposedAt_iff_exists_strictSupportsAt
    {V : Type*} {p : V → Plane} {i : V} :
    StrictlyExposedAt p i ↔
      ∃ u : Plane, StrictSupportsAt p i u := by
  rfl

/-- Two distinct vertices cannot share one strict supporting vector. -/
theorem no_common_strict_support
    {V : Type*} {p : V → Plane}
    {i j : V} (hij : i ≠ j)
    {u : Plane}
    (hi : StrictSupportsAt p i u)
    (hj : StrictSupportsAt p j u) :
    False := by
  have hijPos := hi j hij
  have hjiPos := hj i hij.symm
  have hneg :
      p i - p j = -(p j - p i) := by
    abel
  rw [hneg, inner_neg_right] at hjiPos
  linarith

/-- Left endpoint of the open parameter interval of supporting directions dual
to a same-sign ray interval. -/
def supportParamLeft (a width : ℝ) : ℝ :=
  a + width - Real.pi / 2

/-- Right endpoint of the dual support interval. -/
def supportParamRight (a : ℝ) : ℝ :=
  a + Real.pi / 2

/-- The dual support interval has length exactly pi-width. -/
theorem support_param_width
    (a width : ℝ) :
    supportParamRight a - supportParamLeft a width =
      Real.pi - width := by
  simp [supportParamLeft, supportParamRight]
  ring

/-- Every parameter in the dual open interval is a strict supporting vector. -/
theorem strictSupportsAt_of_common_signed_interval_parameter
    {V : Type*} {p : V → Plane}
    {i : V} {a width phi : ℝ}
    (hwidth0 : 0 ≤ width)
    (hwidthpi : width < Real.pi)
    (sigma : Bool)
    (hphiLo : supportParamLeft a width < phi)
    (hphiHi : phi < supportParamRight a)
    (hrepr : ∀ j, j ≠ i →
      ∃ rho : ℝ, ∃ theta : ℝ,
        0 < rho ∧
        a ≤ theta ∧ theta ≤ a + width ∧
        p j - p i =
          rho • signedRayDirection sigma theta) :
    StrictSupportsAt p i
      (signedRayDirection sigma phi) := by
  intro j hji
  obtain ⟨rho, theta, hrho, hthetaLo, hthetaHi, hreprj⟩ :=
    hrepr j hji
  have hdiff :
      |phi - theta| < Real.pi / 2 := by
    rw [abs_lt]
    constructor
    · unfold supportParamLeft at hphiLo
      linarith
    · unfold supportParamRight at hphiHi
      linarith
  have hinner :
      0 <
        inner ℝ
          (signedRayDirection sigma phi)
          (signedRayDirection sigma theta) := by
    rw [inner_signedRayDirection_same]
    apply Real.cos_pos_of_mem_Ioo
    rw [abs_lt] at hdiff
    exact hdiff
  rw [hreprj, inner_smul_right]
  exact mul_pos hrho hinner

/-- The open support-direction image generated by one signed parameter
interval. -/
def supportDirectionSet
    (sigma : Bool) (left right : ℝ) : Set Plane :=
  {u | ∃ phi : ℝ,
      left < phi ∧ phi < right ∧
      u = signedRayDirection sigma phi}

/-- Abstract disjointness principle: if every vector in two direction sets
strictly supports two different vertices, the sets are disjoint. -/
theorem strict_support_direction_sets_disjoint
    {V : Type*} {p : V → Plane}
    {i j : V} (hij : i ≠ j)
    (Si Sj : Set Plane)
    (hi : ∀ u ∈ Si, StrictSupportsAt p i u)
    (hj : ∀ u ∈ Sj, StrictSupportsAt p j u) :
    Disjoint Si Sj := by
  rw [Set.disjoint_left]
  intro u hui huj
  exact no_common_strict_support hij (hi u hui) (hj u huj)

/-- The entire dual parameter arc of a common signed ray interval maps to
strict supporting vectors. -/
theorem supportDirectionSet_strictly_supports
    {V : Type*} {p : V → Plane}
    {i : V} {a width : ℝ}
    (hwidth0 : 0 ≤ width)
    (hwidthpi : width < Real.pi)
    (sigma : Bool)
    (hrepr : ∀ j, j ≠ i →
      ∃ rho : ℝ, ∃ theta : ℝ,
        0 < rho ∧
        a ≤ theta ∧ theta ≤ a + width ∧
        p j - p i =
          rho • signedRayDirection sigma theta) :
    ∀ u ∈ supportDirectionSet sigma
        (supportParamLeft a width)
        (supportParamRight a),
      StrictSupportsAt p i u := by
  intro u hu
  rcases hu with ⟨phi, hphiLo, hphiHi, rfl⟩
  exact strictSupportsAt_of_common_signed_interval_parameter
    hwidth0 hwidthpi sigma hphiLo hphiHi hrepr

#print axioms no_common_strict_support
#print axioms support_param_width
#print axioms strictSupportsAt_of_common_signed_interval_parameter
#print axioms strict_support_direction_sets_disjoint
#print axioms supportDirectionSet_strictly_supports

end JSP000404Research
